# Generated by Django 5.0.4 on 2024-04-19 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date",
            new_name="created_at",
        ),
    ]
