# Generated by Django 5.0.4 on 2024-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_rename_date_post_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
