# Generated by Django 5.0.4 on 2024-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_options_alter_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated_at",
            new_name="modified",
        ),
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
