# Generated by Django 5.0.4 on 2024-04-22 11:37

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_post_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="read_time",
            field=models.CharField(default="5", max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
