# Generated by Django 5.0.4 on 2024-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_alter_post_body"),
        ("users", "0004_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="users.tag"),
        ),
    ]
