# Generated by Django 5.0.4 on 2024-04-19 04:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LikedItem",
            new_name="Like",
        ),
        migrations.RenameIndex(
            model_name="like",
            new_name="users_like_content_2fb2f4_idx",
            old_name="users_liked_content_73b9c0_idx",
        ),
    ]
