# Generated by Django 5.0.4 on 2024-04-21 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
    ]
