# Generated by Django 5.0.4 on 2024-04-22 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_alter_comment_options_alter_reply_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date", "-modified"]},
        ),
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["-date", "-modified"]},
        ),
    ]
